// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPXhtyCoVmY5XZzVusMmJKtvHEXXyJ9c',
    appId: '1:1072737310103:web:6e4ac753e652242b25e0d2',
    messagingSenderId: '1072737310103',
    projectId: 'app-movie-library',
    authDomain: 'app-movie-library.firebaseapp.com',
    storageBucket: 'app-movie-library.appspot.com',
    measurementId: 'G-3VD3MPDBDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5BDV1XkqDMcgnSIwX0a79aBrzBT_vt8Y',
    appId: '1:1072737310103:android:233eb37d44ed02cb25e0d2',
    messagingSenderId: '1072737310103',
    projectId: 'app-movie-library',
    storageBucket: 'app-movie-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALvjKMKd2pFAbDCHu784rEJnsAjxLXO9E',
    appId: '1:1072737310103:ios:4a42d48926315efc25e0d2',
    messagingSenderId: '1072737310103',
    projectId: 'app-movie-library',
    storageBucket: 'app-movie-library.appspot.com',
    iosClientId: '1072737310103-joiorcv7cjnqm4hfs6vlrkaa99fgjs76.apps.googleusercontent.com',
    iosBundleId: 'com.edjavu.movieLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALvjKMKd2pFAbDCHu784rEJnsAjxLXO9E',
    appId: '1:1072737310103:ios:4a42d48926315efc25e0d2',
    messagingSenderId: '1072737310103',
    projectId: 'app-movie-library',
    storageBucket: 'app-movie-library.appspot.com',
    iosClientId: '1072737310103-joiorcv7cjnqm4hfs6vlrkaa99fgjs76.apps.googleusercontent.com',
    iosBundleId: 'com.edjavu.movieLibrary',
  );
}
